<?= isset($error) ? '<div class="alert alert-warning">' . $this->escapeHtml($error) . '</div>' : '' ?>
<?=
$this->rcmTextEdit(
    'loginHeader',
    'Login',
    'h1'
)
?>
<script>
    // This was moved to AJAX from a normal form post to try to work around chrome "stalled pending forever" issues
    window.addEventListener('DOMContentLoaded', function (event) {
        var formEle = document.body.querySelectorAll('form.loginForm.rcm-login-form')[0];
        formEle.addEventListener('submit', function (event) {
            event.preventDefault();

            function getInputValue(inputName) {
                return document.body.querySelectorAll('form.loginForm.rcm-login-form input[name=' + inputName + ']')[0]
                    .value;
            }

            function redirectBackHereWithError(detailedErrorCode){
                window.location.href = location.protocol + '//' + location.host + location.pathname
                    + '?errorCode=systemFailure&detailedErrorCode='+detailedErrorCode;
            }

            formEle.classList.add('processing');
            fetch('/rcm-login/login-form-submit-handler', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                credentials: 'same-origin',
                body: JSON.stringify({
                    redirect: getInputValue('redirect'),
                    csrf: getInputValue('csrf'),
                    username: getInputValue('username'),
                    password: getInputValue('password')
                })
            }).then(function (response) {
                response.json().then(function (reponseBody) {
                    window.location.href = reponseBody.redirectToUrl;
                }).catch(function(error){
                    redirectBackHereWithError('serverReturnedInvalidJson');
                })
            }).catch(function (error) {
                redirectBackHereWithError('browserCouldNotCommunicateWithServer');
            })
        })
    });
</script>
<div class="loginContent">
    <form class="loginForm rcm-login-form">
        <?=
        $this->rcmTextEdit(
            'userNameCopy',
            'Username:',
            'label',
            array('for' => 'rcmLoginUsername')
        ) ?>
        <br>
        <input type="hidden" name="redirect" value="<?= $this->escapeHtmlAttr($redirect) ?>"/>
        <input type="hidden" name="csrf" value="<?= $this->escapeHtmlAttr($csrf) ?>"/>
        <input autofocus type="text" name="username" value="<?= $this->escapeHtmlAttr($username) ?>"/>
        <br>
        <?=
        $this->rcmTextEdit(
            'loginPasswordCopy',
            'Password:',
            'label',
            array('for' => 'rcmLoginPassword')
        ) ?>
        <br>
        <input type="password" name="password"/>
        <br>
        <br>
        <button class="loginButton btn btn-primary" type="submit">
            <?= $this->translate('Login') ?>
        </button>
    </form>
</div>
<div class="loginFooter">
    <?=
    $this->rcmRichEdit(
        'bottomLoginText',
        '<a href="/reset-password">Forgot your password?</a><br>'
    )
    ?>
</div>
