<!-- <rcm-admin-panel-content> -->
<div class="container-fluid">
    <div class="row rcmAdminPanelNav">
        <div class="col-sm-6 rcm-admin-menu-col rcm-admin-menu-nav-col">
            <?=
            $this->render(
                'rcm-admin/admin/partial/navigation/navigation.phtml'
            ); ?>
            <div class="clearfix"></div>
        </div>
        <div class="col-sm-6 rcm-admin-menu-col rcm-admin-menu-button-col">
            <?php include 'buttons.phtml'; ?>
            <?php include 'revision-list.phtml'; ?>
            <?php include 'page-not-public-warning.phtml'; ?>

        </div>
    </div>
    <div class="row rcmPanelEditorToolbar">
        <div class="col-sm-12 rcm-admin-menu-col rcm-admin-menu-toolbar">
            <div data-html-editor-toolbar
                 data-html-editor-toolbar-toggle="false"
                 data-html-editor-toolbar-default-skin="lightgray">
            </div>
        </div>
    </div>
</div>
<!-- </rcm-admin-panel-content> -->
