<script type="text/javascript" src="/modules/rcm/js/admin/save-as-template.js"></script>
<div id="rcmSaveTemplateWizard">
    <form action="" method="post" id="newPageWizard">
        <div id="rcmSaveTemplateError" style="display: none; text-align: center;">

        </div>

        <div id="newSaveTemplateIndicator" style="float: right;">&nbsp;</div>
        <p>Template Name:
            <input class="rcmTemplateNameInput"
                   type="text"
                   name="rcmTemplateName"
                   id="rcmTemplateNameInput" value=""
                    />

        </p>

        <p>&nbsp;</p>
    </form>
</div>