<script type="text/javascript" src="/modules/rcm/js/admin/new-page-wizard.js"></script>

<div id="rcmNewFromTemplateWizard">
    <form action="" method="post" id="newPageWizard">
        <div id="rcmNewFromTemplateErrorLine" style="display: none; text-align: center;">

        </div>
        <table width="100%">
            <tr>
                <td valign="middle" width="150"><p> Page URL:</p></td>
                <td valign="middle">
                    <input class="rcmNewFromTemplateInput"
                           type="text"
                           name="rcmNewFromTemplateUrl"
                           id="rcmNewFromTemplateUrl" value=""
                            />
                </td>
                <td valign="middle"><p id="rcmNewFromTemplateValidatorIndicator">&nbsp;</p></td>
            </tr>
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
            <tr>
                <td valign="middle"><p>Page Title:</p></td>
                <td valign="middle">
                    <input class="rcmNewFromTemplateInput"
                           type="text"
                           name="rcmNewFromTemplatePageName"
                           id="rcmNewFromTemplateName"
                           value=""
                            />
                </td>
                <td valign="middle"></td>
            </tr>
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
            <tr>
                <td valign="middle"><p>Select Template:</p></td>
                <td valign="middle">
                    <select name="rcmPageRevision" id="rcmPageRevision">

                        <?php foreach ($this->rcmTemplates as $template) : ?>
                            <option value="<?php echo $template->getPublishedRevision()->getPageRevId(); ?>"><?php echo $template->getName() ?></option>
                        <?php endforeach; ?>

                        <option value="-1">Blank Page (Experts Only)</option>';

                    </select>
                </td>
                <td valign="middle"></td>
            </tr>
        </table>

        <div id="rcmNewPageLayoutSelector">
            <p>&nbsp;</p>
            <?php foreach ($this->newPageLayoutContainers as $newLayoutKey => $newLayout) : ?>
                <div class="rcmNewPageLayoutWrapper">
                    <div class="rcmNewPageLayoutContainer">
                        <div class="rcmNewPageLinkOverlay"></div>
                        <img src="<?php echo $newLayout['screenShot']; ?>" /> <br />
                        <?php echo $newLayout['display'] ?>
                        <input type="hidden" name="'.$newLayoutKey.'" value="N" class="rcmLayoutKeySelector" />
                    </div>
                </div>
            <?php endforeach; ?>

            <div style="clear: both;"></div>
        </div>

        <input type="hidden" name="rcmNewPageSelectedLayout" id="rcmNewPageSelectedLayoutInput" value="" />
    </form>
</div>