<?php
/**
 * Admin layout for the Content manager.  This is needed to wrap the site
 * with an editor for admins.
 */


/*
 * Main Content Manager Files
 */
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm/js/admin/config.js',
    'text/javascript'
);

$this->headLink()->appendStylesheet(
    $this->basePath(). '/modules/rcm/css/admin/admin-toolbar.css'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm/js/admin/content-manager2.js',
    'text/javascript'
);

$this->headLink()->appendStylesheet(
    $this->basePath(). '/modules/rcm/css/admin/cm-admin.css'
);


/*
 * Jquery Plugins used by the Content Manager
 */
$this->headScript()->prependFile(
    $this->basePath() . '/modules/rcm/js/admin/prompt-helper.js',
    'text/javascript'
);

$this->headScript()->prependFile(
    $this->basePath()
        .'/modules/rcm/vendor/medialize-jquery-context-menu/src/jquery.'
        .'contextMenu.js'
    , 'text/javascript'
);

$this->headLink()->prependStylesheet(
    $this->basePath()
        .'/modules/rcm/vendor/medialize-jquery-context-menu/src/jquery.'
        .'contextMenu.css'
);


/*
 * WYSIWYG Editors
 */

if ($this->adminRichEditor == 'tinyMce') {

    /*
    * TinyMce
    */

    $this->headScript()->appendFile(
        $this->basePath()
            . '/modules/rcm/vendor/tinymce/jscripts/tiny_mce/jquery.tinymce.js',
        'text/javascript'
    );



    $this->headScript()->appendFile(
        $this->basePath() . '/modules/rcm/js/admin/rcm-tinymce.js',
        'text/javascript'
    );


    $this->headScript()->appendScript(
        'var rcmEditor = new RcmTinyMceEditor(rcmTinyMceConfig);',
        'text/javascript'
    );

} elseif ($this->adminRichEditor == 'aloha') {

    /*
     * Aloha - Not quite Ready for CMS use.  Leaving here as place holders
     * for when it is ready to go.
     */

    $this->headLink()->appendStylesheet(
        $this->basePath(). '/modules/rcm/vendor/aloha/css/aloha.css'
    );

    $this->headScript()->setAllowArbitraryAttributes(true)->appendFile(
        $this->basePath() . '/modules/rcm/vendor/aloha/lib/require.js',
        'text/javascript',
        array(
            'data-aloha-plugins'
            => 'common/ui,common/format,common/highlighteditables,common/link'
        )
    );

    $this->headScript()->appendFile(
        $this->basePath() . '/modules/rcm/vendor/aloha/lib/aloha.js',
        'text/javascript'
    );

    $this->headScript()->appendFile(
        $this->basePath() . '/modules/rcm/js/admin/rcm-aloha.js',
        'text/javascript'
    );

    $this->headScript()->appendScript(
        'var rcmEditor = new RcmAlohaEditor("");',
        'text/javascript'
    );

} else {

    /*
    * Ckeditor
    */
    $this->headScript()->appendFile(
        $this->basePath() . '/modules/rcm/vendor/ckeditor/ckeditor.js',
        'text/javascript'
    );

    $this->headScript()->appendFile(
        $this->basePath() . '/modules/rcm/vendor/ckeditor/adapters/jquery.js',
        'text/javascript'
    );

    $this->headScript()->appendFile(
        $this->basePath() . '/modules/rcm/js/admin/rcm-ckeditor.js',
        'text/javascript'
    );

    $this->headScript()->appendScript(
        'var rcmEditor = new RcmCkEditor(rcmCkConfig);',
        'text/javascript'
    );
}

/**
 * @todo - Move to view helper.  Too much code for view template
 */
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
$hasSiteJs = array();
$hasPageJs = array();

foreach($child->plugins as $container => $orders){
    /** @var \Rcm\Entity\PluginInstance $pluginInstance */
    foreach ($orders as $pluginInstance) {
        if ($pluginInstance->hasAdminJs()) {
            $this->headScript()->appendFile(
                $this->basePath() . $pluginInstance->getAdminEditJs(),
                'text/javascript'
            );

            $hasPageJs[$pluginInstance->getName()] = $pluginInstance->getName();

        }

        if ($pluginInstance->hasAdminCss()) {
            $this->headLink()->appendStylesheet(
                $this->basePath() . $pluginInstance->getAdminEditCss()
            );
        }
    }
}

?>

<script type="text/javascript">

$(function(){
    window.rcmEdit = new RcmEdit(rcmConfig);
    rcmEdit.setLanguage('<?php echo $this->language; ?>');
    rcmEdit.setPage('<?php echo $this->page->getName(); ?>');
    rcmEdit.setPageRevision('<?php echo $this->pageRevision; ?>');
    rcmEdit.setNewInstanceId(<?php echo $this->newPluginCount ?>);
    rcmEdit.setEditor(rcmEditor);
    rcmEdit.setNewPluginInstanceAjaxPath('<?php echo $this->url(
        'contentManagerNewInstanceAjax'
    ) ?>');
    rcmEdit.init();
});


</script>

<?php require 'newPageWizard.phtml'; ?>
<?php require 'newTemplateWizard.phtml'; ?>
<?php require 'saveTemplateWizard.phtml'; ?>

<div id="ContentManagerTopAdminPanel">

    <div id="rcmAdminMenuBar">
        <?php echo $this->adminTitleBar($this->page, $this->pageRevision, $this->language); ?>

        <ul id="rcmAdminMenu">
            <?php echo $this->addAdminNavigation($this->adminPanel); ?>
        </ul>

        <div class="editSaveCancel">

            <div id="rcmAdminToolbarEdit">
                <a href="#" class="rcmEditButton">Edit</a>
            </div>

            <div id="rcmAdminToolbarSaveCancel">
                <a href="#" class="rcmSaveButton">Save</a>
                <a href="#" class="rcmCancelButton">Cancel</a>
            </div>

            <div id="rcmAdminToolbarPleaseWait">
                <p>Please wait...</p>
            </div>
        </div>
    </div>
    <div id="ckEditortoolbar"></div>

</div>

<div id="ToolBarSpacer"></div>

    <div id="rcmLayoutEditorContainer">
        <div id="rcmLayoutEditorColumn">
            <?php echo $this->renderLayoutEditorContainers($this->layoutContainers) ?>
        </div>
    </div>

    <div id="RcmRealPage">
        <?php echo $this->MainPageBody ?>
    </div>


<div id="ckEditorfooter"></div>


