<div id="rcmNewFromTemplateWizard" style="position: absolute; left: -999999px;">
    <form action="" method="post" id="newPageWizard">
        <div id="rcmNewFromTemplateErrorLine" style="display: none; text-align: center;">

        </div>
        <table width="100%">
            <tr>
                <td valign="middle"><p> Page URL:</p></td>
                <td valign="middle">
                    <input class="rcmNewFromTemplateInput"
                           type="text"
                           name="rcmNewFromTemplateUrl"
                           id="rcmNewFromTemplateUrl" value=""
                        />
                </td>
                <td valign="middle"><p id="rcmNewFromTemplateValidatorIndicator">&nbsp;</p></td>
            </tr>
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
            <tr>
                <td valign="middle"><p>Page Title:</p></td>
                <td valign="middle">
                    <input class="rcmNewFromTemplateInput"
                           type="text"
                           name="rcmNewFromTemplatePageName"
                           id="rcmNewFromTemplateName"
                           value=""
                        />
                </td>
                <td valign="middle"></td>
            </tr>
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
            <tr>
                <td valign="middle"><p>Select Template:</p></td>
                <td valign="middle">
                    <select name="rcmPageRevision" id="rcmPageRevision">
                        <?php foreach ($this->rcmTemplates as $template) :?>
                            <option value="<?php echo $template->getPublishedRevision()->getPageRevId(); ?>"><?php echo $template->getName(); ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
                <td valign="middle"></td>
            </tr>
        </table>

    </form>

</div>