<div id="rcmSaveTemplateWizard" style="position: absolute; left: -999999px;">
    <form action="" method="post" id="newPageWizard">
        <div id="rcmSaveTemplateError" style="display: none; text-align: center;">

        </div>

        <div id="newSaveTemplateIndicator" style="float: right;">&nbsp;</div>
        <p>Template Name:
            <input class="rcmTemplateNameInput"
               type="text"
               name="rcmTemplateName"
               id="rcmTemplateNameInput" value=""
            />

        </p>

        <p>&nbsp;</p>
    </form>
</div>