<?php
/**
 * Home page layout
 *
 * Guest Site Home Page Layout
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Application\view\page-layout
 * @author    Westin Shafer <wshafer@inc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci..com/confluence
 */
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm/js/rcm.js', 'text/javascript'
);

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm/generic-site/css/style.css'
);
?>

<div id="aboveNav">
    <?php echo $this->addLayoutContainer(1); ?>
</div>

<div id="navWrap">
    <div id="nav">
        <?php echo $this->addLayoutContainer(2); ?>
    </div>
</div>

<div id="TopSpacer"></div>

<div id="mainCols">

    <div id="rightCol">
        <?php echo $this->addLayoutContainer(5); ?>
    </div>

    <div id="centerCol">
        <?php echo $this->addLayoutContainer(6) ?>
    </div>
</div>

<div id="footWrap">
    <div id="foot">
        <?php echo $this->addLayoutContainer(3); ?>
    </div>
</div>

<div id="belowFoot">
    <?php echo $this->addLayoutContainer(4); ?>
</div>
