<div class="switch-user panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Switch User Page</h3>
    </div>
    <div class="panel-body">
        <div rcm-switch-user-admin=""
             show-switch-to-user-name-field="true"
             switch-to-user-name="''"
             switch-to-user-name-placeholder="'Username'"
             switch-to-user-name-button-label="'Switch to User'"
             switch-back-button-label="'End Impersonation'"
             switch-user-info-content-prefix="'Impersonating:'"
        >
            Switch User
        </div>
    </div>
</div>
