<?php

$this->headScript()->appendFile(
    $this->basePath() . '/rcm-admin/available-block.js'
);

// RcmUser JS
$this->headScript()->appendFile(
    $this->basePath()
    . '/modules/rcm-user/core.js'
);

$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm-admin/admin.js'
);

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-admin/admin.css'
);

$this->headLink()->appendStylesheet(
    $this->basePath()
    . '/modules/rcm-admin/jquery-context-menu/jquery.contextMenu.css'
);
$this->headScript()->appendFile(
    $this->basePath()
    . '/modules/rcm-admin/jquery-context-menu/jquery.contextMenu.js'
);
$this->headScript()->appendFile(
    $this->basePath()
    . '/modules/rcm-admin/jquery-context-menu/jquery.ui.position.js'
);

$layout = $this->layout();

/** @var \Rcm\Entity\Page $page */
$page = $layout->page;

/** @var \Rcm\Entity\Site $site */
$site = $layout->site;

/** @var array $requestedPageData */
$requestedPageData = $layout->requestedPageData;

$getPageData = new \RcmAdmin\Api\GetPageData();

$pageData = $getPageData->__invoke(
    $page,
    $site,
    $requestedPageData
);

$revision = null;
$revisionId = '';
if (!empty($page)) {
    $revision = $page->getCurrentRevision();
    if ($revision instanceof \Rcm\Entity\Revision) {
        $revisionId = $revision->getRevisionId();
    }
}

$this->headMeta()->setProperty(
    'rcm:page',
    json_encode($pageData)
);
?>
<?= $this->render('rcm-admin/admin/partial/panel/panel.phtml'); ?>
<?= $this->render('rcm-admin/admin/partial/dialog/dialog.phtml');
