<?php
$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-login/style.css'
);
?>

<form method="post" action="<?= $_SERVER['REQUEST_URI'] ?>">
    <input name="rcmPluginName" type="hidden" value="RcmCreateNewPassword">
    <div>
        <h1><?= $this->translate('Reset Password') ?></h1>
    </div>


    <?php if ($this->postSuccess): ?>
        <div><?= $this->translate('Your password has been changed.') ?></div>
    <?php else: ?>
        <div class="error">
            <?= isset($error) ? $error : '' ?>
        </div>
        <?php if ($this->hideForm != true): ?>
            <div class="form-group">
                <label for="password"><?= $this->translate('New Password') ?> <?= $this->translate('(letters and numbers only)') ?></label>
                <input id="password" type="password" name="password"/>
            </div>

            <div class="form-group">
                <label for="passwordTwo"><?= $this->translate('Verify Password') ?></label>
                <input id="passwordTwo" type="password" name="passwordTwo"/>
            </div>

            <button class="btn btn-primary"
                    type="submit"><?= $this->translate('Submit') ?>
            </button>
        <?php endif ?>
    <?php endif ?>
</form>
