
<?php

/** @var \Rcm\Entity\Page $page */
$page = $layout->page;

if (empty($page->getPageId())) {
    return;
}

/** @var \Rcm\Entity\Site $site */
$site = $layout->site;
?>
<div class="rcmPanelRightButtons"  data-rcm-admin-menu-actions>
    <div ng-show="rcmAdminPage.editMode">
        <div class="btn-group">
            <button
                class="btn btn-primary btn-xs"
                rcm-admin-edit-button="save"
                ng-disabled="loading"
                type="button"
                >
                <span
                    class="glyphicon glyphicon glyphicon glyphicon-ok"
                    ></span>
                Save Draft
            </button>
            <button
                class="btn btn-xs"
                rcm-admin-edit-button="cancel"
                ng-disabled="loading"
                type="button"
                >
                <span
                    class="glyphicon glyphicon glyphicon-remove"
                    ></span>
                Cancel
            </button>
            <div id="lockPermissionsEditMode"
                 style="<?= (!isset($restrictions)) ? 'display:none'
                     : '' ?>">
                <span class="glyphicon glyphicon-lock"></span>
            </div>
            <div id="unlockPermissionsEditMode"
                 style="<?= (isset($restrictions) && $restrictions == true)
                     ? 'display:none' : '' ?>"><span class="unlock">
                        <img src="/modules/rcm-admin/img/glyphicons_unlock.png" width="14px" height="16px"></span>
            </div>
        </div>
    </div>
    <div ng-hide="rcmAdminPage.editMode">
        <div class="btn-group">
            <?php if ($page->getCurrentRevision()->wasPublished() !== true) : ?>
                <button
                    class="btn btn-primary btn-xs rcmMenuPost publishBtn"
                    type="button"
                    publish-url="<?=
                    $this->url(
                        'RcmAdmin\Page\PublishPageRevision',
                        array(
                            'rcmPageRevision' => $page->getCurrentRevision()->getRevisionId(),
                            'rcmPageType' => $page->getPageType(),
                            'rcmPageName' => $page->getName(),
                        )
                    ); ?>"
                    >
                    <span class="glyphicon glyphicon-check"></span>
                    Publish
                </button>
            <?php endif; ?>
            <button
                class="btn btn-warning btn-xs"
                rcm-admin-edit-button="page"
                ng-disabled="loading"
                type="button"
                >
                <span class="glyphicon glyphicon-edit"></span>
                Edit
            </button>
            <div id="lockPermissionsNonEdit"
                 style="<?= (!isset($restrictions)) ? 'display:none'
                     : '' ?>">
                <span class="glyphicon glyphicon-lock"></span>
            </div>
            <div id="unlockPermissionsNonEdit"
                 style="<?= (isset($restrictions) && $restrictions == true)
                     ? 'display:none' : '' ?>"><span class="unlock">

                        <img src="/modules/rcm-admin/img/glyphicons_unlock.png" width="14px" height="16px"></span>

            </div>
        </div>
    </div>
</div>
<div style="clear: both;"></div>
