<?php

namespace RcmTest\Base;

require_once __DIR__ . '/BaseTestCase.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-08 at 10:11:25.
 */
class DoctrineTestCase extends BaseTestCase
{

    /** @var \Doctrine\Orm\EntityManager */
    public $entityManager;

    protected $expectedTables = array(
        'rcm_admin_allowed_sites',
        'rcm_admin_disallowed_pages',
        'rcm_admin_permissions',
        'rcm_admin_plugin_restrictions',
        'rcm_containers',
        'rcm_containers_revisions',
        'rcm_countries',
        'rcm_domains',
        'rcm_languages',
        'rcm_pages',
        'rcm_pages_revisions',
        'rcm_plugin_instances',
        'rcm_plugin_wrappers',
        'rcm_revisions',
        'rcm_revisions_plugin_wrappers',
        'rcm_setting',
        'rcm_simple_instance_configs',
        'rcm_site_plugin_instances',
        'rcm_sites',
        'rcm_sites_extra_info',
    );

    public function setUp()
    {
        parent::setUp();
        $serviceManager = $this->getServiceManager();
        $this->entityManager = $serviceManager->get('em');
        $this->setupConnection();
    }

    public function setupConnection()
    {
        // Clear Doctrine to be safe
        $this->entityManager->clear();

        // Schema Tool to process our entities
        $tool = new \Doctrine\ORM\Tools\SchemaTool($this->entityManager);
        $classes = $this->entityManager->getMetaDataFactory()->getAllMetaData();

        // Drop all classes and re-build them for each test case
        $tool->dropSchema($classes);
        $tool->createSchema($classes);
    }

    public function testDbSetup()
    {

        $conn = $this->entityManager->getConnection()->getSchemaManager();

        $currentTables = $conn->listTableNames();

        foreach ($this->expectedTables as $table) {
            $this->assertTrue(
                in_array($table, $currentTables, false),
                $table . ' Not found in db memory.'
            );
        }

    }

    public function addExpectedDbTables($tables)
    {
        if (!is_array($tables)) {
            $this->expectedTables[] = $tables;
        } else {
            $this->expectedTables = array_merge($this->expectedTables, $tables);
        }
    }
}