<?php

/**
 * Base layout
 *
 * Acts as the wrapper template for page layouts
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Application\view\layout
 * @author    Westin Shafer <wshafer@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */

$this->headTitle()->setSeparator(' - ')
    ->setAutoEscape(false);

$this->headLink(
    array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/images/favicon.ico',
    )
);
$this->headMeta()->appendName(
    'viewport', 'width=device-width, initial-scale=1.0'
);

/** @var \Rcm\View\Helper\GetRcmRequired $rcmRequired  */
$rcmRequired = $this->getRcmRequired();

echo $this->doctype();
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->metaTitle) ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
</head>

<body>
<?php echo $rcmRequired->getBodyTop(); ?>

<?php echo $this->content; ?>

<?php echo $rcmRequired->getBodyBottom(); ?>
</body>
</html>
