<?php

/**
 * Base layout
 *
 * Acts as the wrapper template for page layouts
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Application\view\layout
 * @author    Westin Shafer <wshafer@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */

$this->headTitle()->setSeparator(' - ')
    ->setAutoEscape(false);

$basePath = $this->basePath();


$this->headLink(
    array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $basePath . '/images/favicon.ico',
    )
);

// HTML5 shim, for IE6-8 support of HTML elements
$this->headScript()->appendFile(
    $basePath . '/js/html5.js', 'text/javascript',
    array('conditional' => 'lt IE 9',)
);

$this->headScript()->prependFile(
    $this->basePath() . '/modules/rcm/vendor/jquery-block-ui/jquery.blockUI.js', 'text/javascript'
);
$this->headScript()->prependFile(
    $basePath . '/modules/rcm/vendor/jquery/js/jquery-ui-1.8.24.custom.min.js', 'text/javascript'
);

$this->headScript()->prependFile(
    $basePath . '/modules/rcm/vendor/jquery/js/jquery-1.8.2.min.js', 'text/javascript'
);

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm/vendor/jquery/css/smoothness/jquery-ui-1.8.21.custom.css'
);



$this->headMeta()->appendName('description', $this->metaDesc);

$this->headMeta()->appendName('keywords', $this->metaKeys);

$this->headMeta()->appendName(
    'viewport', 'width=device-width, initial-scale=1.0'
);

echo $this->doctype();
?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="/favicon.ico" >
    <?php echo $this->headTitle($this->metaTitle) ?>

    <?php echo $this->headMeta() ?>

    <!-- Le styles -->
    <?php echo $this->headLink() ?>

    <!-- Scripts -->
    <?php echo $this->headScript() ?>

</head>

<body>

<?php echo $this->content; ?>

</body>
</html>
