<?php

/**
 * Base layout
 *
 * Acts as the wrapper template for page layouts
 *
 * PHP version 5.3
 *
 * LICENSE: No License yet
 *
 * @category  Reliv
 * @package   Application\view\layout
 * @author    Westin Shafer <wshafer@relivinc.com>
 * @copyright 2012 Reliv International
 * @license   License.txt New BSD License
 * @version   GIT: <git_id>
 * @link      http://ci.reliv.com/confluence
 */

$this->headTitle()->setSeparator(' - ')
    ->setAutoEscape(false);

$this->headLink(
    array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/images/favicon.ico',
    )
);
$this->headMeta()->appendName(
    'viewport', 'width=device-width, initial-scale=1.0'
);

/** @var \Rcm\View\Helper\rcmViewInit $rcmRequired  */
$rcmRequired = $this->rcmViewInit();

/** Theme  **/
$this->headScript()->appendFile(
    $this->basePath() . '/modules/rcm/js/rcm.js', 'text/javascript'
);

$this->headLink()->appendStylesheet($this->basePath() . '/modules/rcm-generic/css/layout.css');

echo $this->doctype();
?>

<html lang="en">
<!-- Website template by freewebsitetemplates.com -->

<head>
    <meta charset="utf-8">
    <?=  $this->headTitle($this->metaTitle) ?>
    <?=  $this->headMeta() ?>
    <?=  $this->headLink() ?>
    <?=  $this->headScript() ?>
</head>

<body>

<!--Required CMS Body Top-->
<?=  $this->rcmTop; ?>

<!--Main Theme Body-->
<div id="sitewrapper">
    <div id="rcmGenTopHeader">
        <?=  $this->getLayoutContainer(1); ?>
    </div>

    <div id="rcmGenMainBody">
        <?=  $this->getLayoutContainer(2); ?>
    </div>

    <div id="rcmGenFooter">
        <?=  $this->getLayoutContainer(3); ?>
    </div>
</div>

<!--Required CMS Body Bottom-->
<?=  $this->rcmBottom; ?>

</body>
</html>
